# Generated by Django 5.1.7 on 2025-03-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
    ]
