# Generated by Django 5.1.7 on 2025-04-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_purchase_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image_path',
            field=models.URLField(blank=True, null=True),
        ),
    ]
