# Generated by Django 5.1.7 on 2025-04-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_property_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
    ]
