# Generated by Django 5.2 on 2025-04-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
