# Generated by Django 5.2 on 2025-04-11 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property'),
        ),
    ]
