# Generated by Django 5.2 on 2025-04-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_property_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='transaction_type',
            field=models.CharField(default='بيع', max_length=50),
        ),
    ]
